### ISSUE TITLE
Custom dataset mtbs_1984_2018 not found

### ISSUE THREAD

**Issue by giswqs** [aazuspan/sankee#4]
I was testing the custom dataset example, and it seems the asset `'users/aazuspan/fires/mtbs_1984_2018'` is not accessible. Would you mind sharing this dataset? Thanks. 

![image](https://user-images.githubusercontent.com/5016453/117747733-b571fd00-b1dc-11eb-8b5b-514eae2af216.png)

**Comment by aazuspan** [comment]
@giswqs Oops, it should be available now. Thanks for letting me know!

**Comment by giswqs** [comment]
Thanks for your prompt response. It works now. 

BTW, I ran the Premade Dataset example, the plot I got looks very different from yours. Do you know why?

Yours:
![image](https://user-images.githubusercontent.com/5016453/117748484-1948f580-b1de-11eb-999e-105dc5f8ccc4.png)

Mine:
![newplot](https://user-images.githubusercontent.com/5016453/117748507-21089a00-b1de-11eb-9eed-c4d94ba36f9b.png)

**Comment by aazuspan** [comment]
It looks like the example code was sampling a different region than the figure. I updated the example code to use the correct location, so the figures should match now. Sorry for the confusion!

**Comment by giswqs** [comment]
Thanks for the fix. BTW, sankee has been integrated into geemap. Here is a sneak peek. 

https://user-images.githubusercontent.com/5016453/117758825-b14fda80-b1f0-11eb-9b5a-707c677b4a7e.mp4

**Comment by aazuspan** [comment]
Wow, that looks great! I'm excited to try it.

One thing to consider: NLCD1992 uses a slightly different legend than later years (see Table 1 [here](https://pubs.usgs.gov/of/2008/1379/pdf/ofr2008-1379.pdf) for a crosswalk). For that reason, NLCD1992 isn't usable with sankee unless you set up a custom dataset because it contains some values that aren't defined by NLCD2016. I had hoped to implement a function in sankee for converting NLCD1992 to match the NLCD2016 legend, but haven't had a chance.
